# 使用Alpine作为基础镜像
FROM alpine:latest

# 设置工作目录
WORKDIR /app

# 复制预构建的二进制文件
COPY otter .

# 复制前端构建产物
COPY web/dist ./web

# 设置二进制文件可执行权限
RUN chmod +x /app/otter

# 暴露端口
EXPOSE 8086

# 设置环境变量
ENV PORT=8086
ENV JWT_SECRET=your-secret-key

# 启动应用程序
CMD ["sh", "-c", "./otter -dsn $DSN -port $PORT -jwt-secret $JWT_SECRET"]
